name: odata_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-180.0.dev

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
