name: odata_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-180.0.dev

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.13.0
  supabase_flutter: ^2.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5
  flutter_launcher_icons: ^0.14.4
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.1
  latlong2: ^0.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
